### ISSUE TITLE
Brique Internet Android

### ISSUE THREAD

**Issue by qwertygc** [labriqueinternet/labriqueinter.net#1]
Hello ! Je ne savais pas où poser la question, donc je pose ici : 

Je souhaite faire une Brique Internet en recyclant un vieux téléphone sous android. Je me posais donc la question suivante : si je configure un VPN et que je partage ma connexion, est-ce que les personnes se connectant sur le wifi généré par mon téléphone passerait par le VPN ?

La même question se pose avec Tor, si j'installe Orbot et que je partage ma connexion, mes contacts passerait par TOR ?

Cordialement,

Qwerty

**Comment by jvaubourg** [comment]
Salut. On va mettre en place une liste de diffusion, pour ce genre de questions.

Si tu passes par ton VPN ou Tor quand tu utilises ton téléphone, il n'y a pas de raison que ça ne soit pas également le cas pour ceux qui l'utilisent via ton hotspot. En particulier pour ton application VPN, elle modifie probablement la route par défaut et ce sera la même pour tout le monde. Après, on ne peut jamais prévoir les montages un peu bizarres, surtout sur ce genre de système à moitié fermé.

Pour vérifier que tu passes bien par Tor au bout du fil, tu peux utiliser cette adresse web : https://check.torproject.org
