### ISSUE TITLE
Redirect internetcu.be to the English version

### ISSUE THREAD

**Issue by jvaubourg** [labriqueinternet/labriqueinter.net#13]
Accessing to the website through "internetcu.be" rather than "labriqueinter.net" should redirect to "/en.html".

**Comment by sbadia** [comment]
``` short
❯ dig +short a internetcu.be
```

@Psycojoker could you add a `A` record on `212.129.0.109` ?

**Comment by Psycojoker** [comment]
@sbadia done :)

**Comment by sbadia** [comment]
done ! http://internetcu.be/
