### ISSUE TITLE
Accessibility: website appears to be hard to read because of the contrast and the font

### ISSUE THREAD

**Issue by Psycojoker** [labriqueinternet/labriqueinter.net#17]
Hello,

Kload and I made a presentation to people with their age around 50-60 yesterday, one of the feedback we got was that http://labriqueinter.net was hard to read because of:
- black background
- very thin font

It might also be due to other reasons, my knowledge of accessibility is low.

Kind regards

**Comment by jvaubourg** [comment]
Feel free to propose a PR for changing the main font. We could keep the Jura font only for the text above the video and the titles.

**Comment by Psycojoker** [comment]
Font choice is probably my worst skill ever in design related things, otherwise I would have done/suggest something :/

I guess that "comic sans ms" doesn't count as a good choice.

**Comment by jvaubourg** [comment]
I propose this simple solution:

cf171f60d2bece2ed8e34fe8efacf3a421cc5393 / http://labriqueinter.net

**Comment by Psycojoker** [comment]
Looks better for me :)

I'm sending an email to the one who've made the comment.

**Comment by Psycojoker** [comment]
To quote the answer:

> merci beaucoup d'avoir pensé à cette question et de m'avoir fait parvenir le lient de LaBrique, après la modification.
> 
> Cette fois, c'est facilement lisible. Super. Merci.

I guess that this issue is fixed.

Thanks :)
