### ISSUE TITLE
Please provide instructions on how to install the image onto the brique

### ISSUE THREAD

**Issue by mquinson** [labriqueinternet/labriqueinter.net#24]
I think I have all pieces but that's still a puzzle for me :)

**Comment by Psycojoker** [comment]
Ohai,

I don't know what is planned for the website as we don't have "officiel" installation instructions, but in mean time here is our current resources (nearly all in french): 
- most detailed guide http://pad.aquilenet.fr/p/LaBrique
- the "by hand" guide followed by "used to make installations" users https://github.com/YunoHost/doc/blob/master/installation_brique_fr.md
- the installation scripts we now use (one per isp) https://github.com/labriqueinternet/configuration_scripts

**Comment by mquinson** [comment]
I'm closing my own bug here since the provided explanation are now really good. 
Thanks for your work.
