### ISSUE TITLE
Please provide an easy way to retrieve the IP of the Cube for its installation

### ISSUE THREAD

**Issue by mquinson** [labriqueinternet/labriqueinter.net#28]
The install-sd.sh works like a charm, thanks for that. 

But for the second step of the installation, after the Cube boot, I had to struggle for half an hour to remember the options of nmap. It would be really cool if the install script could provide an option to do the scan for me, or at least if the webpage could give some hints about how to do so.

Thanks for your great work,
Mt

**Comment by randomstuff** [comment]
Would it be meaningful to use avahi for this?

**Comment by mquinson** [comment]
@bleuchtang told me on IRC that he was using arp-scan for this, but I never used it myself. At the end, I seem to remember that did a `nmap -sP 192.168.1.1/24` and then `nmap -O 192.168.1.10` on the hosts found at the first step.

**Comment by jvaubourg** [comment]
The install-sd.sh works like a charm, **and** already provides an option to do the scan for you ;). See the « -l »  option.
