### ISSUE TITLE
Pourriez-vous mettre en place un serveur VPN aussi ?

### ISSUE THREAD

**Issue by HLFH** [labriqueinternet/labriqueinter.net#31]
Coucou,

J'ai vu que LaBriqueInternet ne propose qu'un [client VPN](https://github.com/labriqueinternet/vpnclient_ynh). Or, j'ai besoin de mettre en place un serveur VPN sur La Brique. Est-ce que c'est possible ?

Merci par avance,
HLFH

**Comment by jvaubourg** [comment]
Bonjour,

Il y a une application YunoHost qui s'appelle « OpenVPN », et qui installe un serveur OpenVPN.

Tu devrais directement la trouver dans la liste des applications de YunoHost, quand tu vas dans l'interface d'administration web YunoHost de ta Brique. Honnêtement je ne l'ai jamais essayée sur la Brique, donc je ne garantis rien, mais y'a pas de raison que ça marche pas :).

**Comment by HLFH** [comment]
Ok merci, je vais donc tenter une _brique_ RPI2 basé sur Debian/Yunohost et tester le plugin OpenVPN potentiellement instable. Et comme je préfère ArchLinux, je risque de migrer vers arkOS/ArchLinux ARM dès que possible.

**Comment by jvaubourg** [comment]
Heu, comme tu veux pour arkOS/ArchLinux, mais les applications de la Brique ne seront pas du tout compatibles. Et beaucoup d'autres apps YunoHost aussi je pense.
