### ISSUE TITLE
Add possibility to execute custom script

### ISSUE THREAD

**Issue by SohKa** [labriqueinternet/labriqueinter.net#66]
Hello !

IMHO, the `install-sd.sh` script lacks the possibility to easily execute a custom script at the end of the `hypercube.sh` script.

For example, it would be useful : 
- to include some tweaking (in my case, adding a new routing table)
- to quickly test some stuff (without having to modify the `hypercube.sh`)
- for some local associations, to add their specifics to the Brique installation without having to maintain their own fork of the `hypercube.sh` ([like Neutrinet's folks](https://gitlab.com/Spctrl/neutrinet_cube_install/compare/master...neutrinet_specifics_to_hypercube_sh) )

I know it is possible to use the `-w` parameter to replace the hypercube.sh script with a custom one, but as illustrated earlier, in the long term, it requires to maintain a fork of the hypercube.sh (which is maybe not that time consuming, but it requires someone responsible for it in the local association and it adds more complexity).

I already did some work in the [install-sd.sh](https://github.com/labriqueinternet/labriqueinter.net/compare/master...SohKa:execute-custom-script?expand=1) and in the [hypercube.sh](https://github.com/labriqueinternet/build.labriqueinter.net/compare/master...SohKa:execute-custom-script?expand=1). Could you have a look and tell me if it's acceptable for a merge request ?

**Comment by pitchum** [comment]
I'v tested your changes and merged : https://github.com/labriqueinternet/labriqueinter.net/pull/67

thanks
