### ISSUE TITLE
Hypercube generation - Blank spaces at the start and end of password are disregarded

### ISSUE THREAD

**Issue by Zeriuno** [labriqueinternet/labriqueinter.net#71]
_What happens_
When creating a hypercube, if the password field starts or end with a blank space, the blank space will be removed from the hypercube file

_What should happen_
Linux accepts blank spaces (at the start of the password, at the end, at the middle.
Blank spaces should not be stripped by the hypercube generator.

**Comment by keomabrun** [comment]
moved there: https://github.com/labriqueinternet/install.labriqueinter.net/issues/2
